version: "3.7"
services:
  database:
    build:
      context: ./db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8090:8090"
volumes:
  data:
